languageCode:           "en"
title:                  "CoreUI"
baseURL:                "https://coreui.io/docs/"
enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/4.0/dist
    - source:           docs/assets
      target:           assets
    - source:           docs/content
      target:           content
    - source:           docs/data
      target:           data
    - source:           docs/layouts
      target:           layouts
    - source:           docs/static
      target:           static
    - source:           docs/static/4.0/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           docs/static/4.0/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "Open Source Ui Components library built on top of Bootstrap 5."
  authors:              "Lukasz Holeczek, Andrzej Kopanski"
  social_image_path:    /4.0/assets/brand/coreui-social.jpg
  social_logo_path:     /4.0/assets/brand/coreui-social-logo.png

  current_version:      "4.0.0-rc.5"
  current_ruby_version: "4.0.0-rc.5"
  docs_version:         "4.0"
  rfs_version:          "9.0.3"
  github_org:           "https://github.com/coreui"
  repo:                 "https://github.com/coreui/coreui"
  twitter:              "core_ui"
  community:            "https://community.coreui.io/"
  blog:                 "https://coreui.io/blog/"
  icons:                "https://icons.coreui.io/"

  download:
    source:             "https://github.com/coreui/coreui/archive/v4.0.0-rc.5.zip"
    dist:               "https://github.com/coreui/coreui/releases/download/v4.0.0-rc.5/coreui-4.0.0-rc.5-dist.zip"

  cdn:
  # See https://www.srihash.org for info on how to generate the hashes
    css:             "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.0.0-rc.5/dist/css/coreui.min.css"
    css_hash:        "sha384-8lW2HtRYKm2n0HJEkt6daDdhOar3RKgX4qrb2l3Ws3f+Wn1flK29F5XN2vFI60Ll"
    css_rtl:         "https://cdn.jsdelivr.net/npm/coreui@4.0.0-rc.5/dist/css/coreui.rtl.min.css"
    css_rtl_hash:    "sha384-ntaYFps+EqwVKMKJu/4d64EBCc7X/C02JUrayLPrua55LrX1+PsS5Gz4f3CxXjp9"
    js:              "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.0.0-rc.5/dist/js/coreui.min.js"
    js_hash:         "sha384-f4hhTnh0MsrJsMwuTv3R5Qr2NGGgGEu1MwDl5uIilNdy6cqpq5WRkQEzdvT6opP9"
    js_bundle:       "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.0.0-rc.5/dist/js/coreui.bundle.min.js"
    js_bundle_hash:  "sha384-JS8SGRZ97zIYgftI4PV4AsrO7UWt7Hicuidh15pho3UU9IVGthC7tECDK5gnmSyV"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    popper_hash:      "sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
