languageCode:           "en"
title:                  "CoreUI"
baseURL:                "https://coreui.io/docs/"
canonifyURLs:           true

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/dist
    - source:           docs/assets
      target:           assets
    - source:           docs/content
      target:           content
    - source:           docs/data
      target:           data
    - source:           docs/layouts
      target:           layouts
    - source:           docs/static
      target:           static
    - source:           docs/static/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           docs/static/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "Open Source Ui Components library built on top of Bootstrap 5."
  authors:              "Lukasz Holeczek, Andrzej Kopanski"
  social_image_path:    /assets/brand/coreui-social.jpg
  social_logo_path:     /assets/brand/coreui-social-logo.png

  current_version:      "4.2.4"
  current_ruby_version: "4.2.4"
  docs_version:         "4.1"
  rfs_version:          "9.0.3"
  github_org:           "https://github.com/coreui/coreui"
  repo:                 "https://github.com/coreui/coreui"
  twitter:              "core_ui"
  opencollective:       "coreui"
  community:            "https://github.com/coreui/coreui/discussions"
  blog:                 "https://coreui.io/blog/"
  icons:                "https://icons.coreui.io/"

  download:
    source:             "https://github.com/coreui/coreui/archive/v4.2.4.zip"
    dist:               "https://github.com/coreui/coreui/releases/download/v4.2.4/coreui-4.2.4-dist.zip"

  download_template:
    website:            "https://coreui.io/product/free-bootstrap-admin-template/"

  cdn:
  # See https://www.srihash.org for info on how to generate the hashes
    css:             "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.2.4/dist/css/coreui.min.css"
    css_hash:        "sha384-PEo/NAKJEN318LeDvYUzENW9J05vrbldkVc8xOWwrQujVv1nuRcTXfVbH8axvSNk"
    css_rtl:         "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.2.4/dist/css/coreui.rtl.min.css"
    css_rtl_hash:    "sha384-Bqf/KsKKm1lO23SM0zVyg6p2lGyrXX8CQwc+/981hPnR5mLGUqA5KuhFryCtyWz0"
    js:              "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.2.4/dist/js/coreui.min.js"
    js_hash:         "sha384-qVaUi0julBP4h0s04mnrTlvDtEOEV4Y7Qha1dxyAeRTV87JfHb6RGCdJP0vue7/6"
    js_bundle:       "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.2.4/dist/js/coreui.bundle.min.js"
    js_bundle_hash:  "sha384-XnSpd7G8ncnmaNrhAS8dlJjDQYu+PgdHUELHmKwWkH8NfvjcbRZV99kucyeq2y29"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    popper_hash:      "sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
